title: TERENCE FARMER
logo: /assets/img/THS-3.jpg
description: Portfolio
show_downloads: false
theme: jekyll-theme-minimal
baseurl: "/terencefarmer.github.io"
alt_logo: "/assets/img/TableauBadge.png"
is_project_page: false
